name: guardian_app
description: "A Society Management Guardian App."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  path_provider: ^2.1.2
  path: ^1.9.0
  google_mlkit_text_recognition: ^0.11.0
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2      # Use this for your DatabaseService logic
  # firebase_database: ^11.3.10  # Only add this if you specifically need Realtime DB

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Standard for current Flutter versions

flutter:
  uses-material-design: true